name: quizsnap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.9.0
  file_picker: ^10.2.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - design.json
    - .env
    - assets/image/logo.png
    - assets/image/quiz.png
    - assets/image/onboarding/ob1.png
    - assets/image/onboarding/ob2.png
    - assets/image/onboarding/ob3.png
